### ISSUE TITLE
Info filters do not appear to be working correctly in many cases

### ISSUE THREAD

**Issue by scm2217** [panoptyk/example-game#13]
![image](https://user-images.githubusercontent.com/10471022/75024468-4d57bf80-544e-11ea-9598-c3e14b330f4b.png)

Some filters seem to only conditionally work, i.e. agent filter only works when room filter is set to something.

![image](https://user-images.githubusercontent.com/10471022/75025296-c4da1e80-544f-11ea-8ba1-bc156527883e.png)
^ The user is not fdas.

**Comment by mitchkm** [comment]
@scm2217 double-check filtering has been fixed when you can.

**Comment by scm2217** [comment]
Seems to be working now
