### ISSUE TITLE
Build tilemap for scenario

### ISSUE THREAD

**Issue by scm2217** [panoptyk/example-game#15]
https://docs.google.com/drawings/d/1sdNlYx737CBL35mzEYjzx5iBz_g7csa_S9U0uIwIFZc/edit?usp=sharing

**Comment by mitchkm** [comment]
"Shot list"
- [ ] Town Center
- [ ] East Residential
- [ ] West Residential
- [ ] South Town
- [ ] N. Town Entrance
- [ ] Cafe
- [ ] Inn
- [ ] Back alley
- [ ] Tavern
- [ ] Tavern (backroom)
- [ ] Tavern (upstairs)
- [ ] Player House

Mitch Specific: 
- [ ] Guild Hall Craftsmen
- [ ] Guild Hall Informants
- [ ] Road Fork
- [ ] Forrest
- [ ] Farm
