### ISSUE TITLE
Tell tab for conversations causing exception for sentence module

### ISSUE THREAD

**Issue by scm2217** [panoptyk/example-game#17]
Need to put a fake "isQuery" function onto partially made question in Conversation tab to prevent non-critical exception from sentence.js

**Comment by mitchkm** [comment]
This is handled in InfoEntry.vue

https://github.com/panoptyk/example-game/blob/6d7b01a5de023b9aeac3950e88f52d3389b5de77/client/ui/components/infoEntry.vue#L30-L40

**Comment by scm2217** [comment]
Somehow fails sometimes 
![image](https://user-images.githubusercontent.com/10471022/75309940-57d7d780-5807-11ea-8ccd-dab9d6211626.png)
