### ISSUE TITLE
ActionState act function is not abstract

### ISSUE THREAD

**Issue by jthpotz** [panoptyk/example-game#4]
There shouldn't be a default act function for ActionState. Any ActionState should always need to define it's own act function.

**Comment by scm2217** [comment]
Well for one (maybe only) counterexample, an IdleState does not want to do anything in act.

**Comment by jthpotz** [comment]
Right, but that isn't a default behavior. That should be defined in the idle action itself.

**Comment by mitchkm** [comment]
Yea this is an oversight by me I think. It should be abstract as anyone extending the ActionState should be forced to think about their act() function
