### ISSUE TITLE
Questionable use of static variables in Behavior constructor

### ISSUE THREAD

**Issue by scm2217** [panoptyk/example-game#6]
Hey John, Mitch and I were discussing bots and think it is not a great idea to be assigning static variables in constructors. Since they function as persistent information between States they should likely be assigned by a strategy or behavior transition function.

https://github.com/panoptyk/example-game/blob/34ee0055bf534230bed85551e506feafb1b89602/bots/john_bots/MapAndMove/Behaviors/moveBehavior.ts#L11-L16

**Comment by jthpotz** [comment]
Changed over to separate static function that gets called in the transition function in the strategy.

See commit 34ee0055bf534230bed85551e506feafb1b89602
